### ISSUE TITLE
Larger datasets to embedefy fails?

### ISSUE THREAD

**Issue by syusuf1234** [embedefy/pgembedefy#5]
process step failed with below:

```
 ERROR:  Embedefy API error: extract_error: failed to extract embedding: Non-zero status code returned while running Add node. Name:'/embeddings/Add_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 512 by 542

```

**Comment by devfacet** [comment]
So there is an open [bug](https://github.com/xenova/transformers.js/issues/355) in the underlying library related to this issue. Until it's fixed, it will fail for columns that have large text in them.

You can also try other models. As far as I know, `e5-small-v2`, `gte-small`, and `all-minilm-l6-v2` have already been fixed for this issue.

P.S.: Note that once the bug is fixed, it will just truncate large texts, which may not be what you want. I strongly suggest chunking columns (e.g., adding a new table) with large text for better accuracy.

**Comment by devfacet** [comment]
Good news! The issue with the `bge-small-en-v1.5` model is solved. Let me know if you are still having the same issue.
